### ISSUE TITLE
An unexpected error occurred: the workbench.html file is different from what was expected. Please ensure that you do not have any other extensions to modify the workbench.html file.

### ISSUE THREAD

**Issue by shaobeichen** [KrautGTI/glass-theme-doyle#4]
Hello, when I install the plugin, it prompts:

An unexpected error occurred: the workbench.html file is different from what was expected. Please ensure that you do not have any other extensions to modify the workbench.html file.

I installed the vscode animation plugin before, which caused the UI of vscode to be modified. Later, I uninstalled it.

When installing the vscode animation plugin before, I also received a notification that it was damaged, so I ignored the notification.

I want to install this plugin now and want to use it on both Windows and Mac simultaneously. I don't know how to solve it. Currently, I encountered it on Windows 10.

I tried using Fix VSCode Checksum, but it didn't seem to work.

**Comment by KrautGTI** [comment]
Generic Windows Bug Update with new version 1.86.0 

I've been digging into the issues with the extension on Windows with VSCode 1.86 and newer. It turns out that Electron 27 introduced some breaking changes affecting how transparent windows are managed on Windows 10/11. This messes with our Glassmorphism theme a bit.

I did find a workaround that makes the extension work with these VSCode versions, but there's a tradeoff – VSCode windows won't be snappable or maximizable. I know this is a major drag, so I'm holding off on pushing this update until I find a better solution.

For now, if you want to keep the Glassmorphism vibes going on Windows, you can roll back to VSCode 1.85.2. Here’s a link to download that version: [https://update.code.visualstudio.com/1.85.2/win32-x64-user/stable](https://update.code.visualstudio.com/1.85.2/win32-x64-user/stable). Install it, enable the extension, and you should be golden.

Will keep you posted as soon as I find a more elegant fix. Thanks for your patience and understanding!
